version: "3.8"

services:
    app:
        build: .
        container_name: ci3_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - CI_ENV=development
            - DB_DRIVER=sqlite3
            - DB_DATABASE=database/montink.db

    mailpit:
        image: axllent/mailpit
        container_name: ci3_mailpit
        restart: unless-stopped
        ports:
            - "1025:1025"  # SMTP port
            - "8025:8025"  # Web UI port
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
